[tool.poetry]
name = "kubecrd"
version = "34.1.0"
description = "Create Kubernetes CRD using Python dataclasses"
authors = ["Abhilash Raj <raj.abhilash1@gmail.com>"]
license = "Apache-2.0"
readme = "README.rst"
repository = "https://github.com/maxking/kubecrd"

[tool.poetry.urls]
"Bug Tracker" = "https://github.com/maxking/kubecrd/issues"

[tool.poetry.dependencies]
python = ">=3.11,<4"
apischema = ">=0.15.0"
PyYAML = ">=6.0"
kubernetes = "^34.1.0"

[tool.poetry.group.dev.dependencies]
pytest = "^8.4.2"
kopf = "^1.38.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
addopts = "--doctest-glob='*.rst'"
