# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  unittest:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11", "3.12", "3.13", "3.14"]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.python-version }}

    - name: KinD (Kubernetes in Docker) Action
      uses: engineerd/setup-kind@v0.6.2
      with:
        version: "v0.30.0"
        name: kind-${{ matrix.python-version }}-${{ github.run_id }}

    - name: Testing
      run: |
        kubectl cluster-info
        kubectl version
        kubectl get pods -n kube-system

    - name: Install Poetry
      uses: snok/install-poetry@v1

    - name: Install dependencies
      run: |
        poetry install
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Test with poetry
      run: |
        poetry run pytest